erDiagram
 dbo_AWBuildVersion {
   SystemInformationID
   Database Version
   VersionDate
   ModifiedDate
 }
 dbo_DatabaseLog {
   DatabaseLogID
   PostTime
   DatabaseUser
   Event
   Schema
   Object
   TSQL
   XmlEvent
 }
 dbo_ErrorLog {
   ErrorLogID
   ErrorTime
   UserName
   ErrorNumber
   ErrorSeverity
   ErrorState
   ErrorProcedure
   ErrorLine
   ErrorMessage
 }
